name: setup
description: Install system and project dependencies

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - uses: Gr1N/setup-poetry@v9

    - uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      shell: bash
      run: make install
