#:kivy 1.8.0

<Cell>:
    rows: 3
    cols: 3

    Button:
        text: "a"
    Button:
        text: "b"
    Button:
        text: "c"
    Button:
        text: "d"
    Button:
        text: "e"
    Button:
        text: "f"
    Button:
        text: "g"
    Button:
        text: "h"
    Button:
        text: "i"


<GridCommand>:

    rows: 3
    cols: 3
    padding: 10
    spacing: 5

    Cell
    Cell
    Cell
    Cell
    Cell
    Cell
    Cell
    Cell
    Cell
