site_name: GridCommand
site_description: TBD
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/gridcommand

theme: mkdocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
