locators:
  inclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
  exclusions:
    - mode: ''
      value: ''
      index: 0
      uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: new_board
    locators:
      - mode: text
        value: New Board
        index: 0
        uses: 2
  - verb: click
    name: start_game
    locators:
      - mode: css
        value: .btn-dark
        index: 0
        uses: 2
  - verb: click
    name: two_players
    locators:
      - mode: id
        value: two-players
        index: 0
        uses: 2
  - verb: click
    name: shared_device
    locators:
      - mode: text
        value: Shared device
        index: 0
        uses: 2
